name: Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  my-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          make build
         # Runs the linter action
      - name: Run Linter
        run: |
          make lint
